Askus.Store/Askus.Store/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Askus.Store.Attributes;
using Askus.Store.Infrastructure.Domain.Publication;
using Askus.Store.Infrastructure.Interface.Exceptions;
using Askus.Store.Infrastructure.Interface.Repositories;
using Askus.Store.Infrastructure.Interface.Services;
using Askus.Store.Infrastructure.ViewModel;

namespace Askus.Store.Controllers
{
    public class PageController : BaseStoreController
    {
        private IDomainRepository<Page> _pageRepository;
        private IPublicationService _publicationService;

        public PageController(
            IDomainRepository<Page> domainRepository,
            IPublicationService publicationService)
        {
            _pageRepository = domainRepository;
            _publicationService = publicationService;
        }

        // GET: Page
        public ViewResult Index()
        {
            return View();
        }

        [AjaxOnly]
        [JsonException]
        [HttpGet]
        public async Task<JsonResult> GetList(FilterVM filter)
        {
            if (filter == null)
                filter = new FilterVM() { Skip = 0, Take = MaxPageCount };

            var data = await _pageRepository.GetFilteredAsync(filter);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        [JsonException]
        [HttpPost]
        public async Task Save(Page item)
        {
            if (item == null)
                throw new ValidationException("Данные не найдены");
            if (string.IsNullOrEmpty(item.ActionName))
                throw new ValidationException("Необходимо указать Action");
            if (string.IsNullOrEmpty(item.ControllerName))
                throw new ValidationException("Необходимо указать Controller");

            await _pageRepository.SaveAsync(item);
        }

        [AjaxOnly]
        [JsonException]
        [HttpPost]
        public async Task Remove(int id)
        {
            var page = await _pageRepository.GetByIdAsync(id);
            await _pageRepository.RemoveAsync(page);
        }

        [AjaxOnly]
        [JsonException]
        [HttpPost]
        public async Task SetPublication(int id)
        {
            var page = await _pageRepository.GetByIdAsync(id);
            await _publicationService.SetPublication(page);
        }

    }
}

Askus.Store/Askus.Store/Controllers/SectionController.cs
using Askus.Store.Attributes;
using Askus.Store.Infrastructure.Domain.Publication;
using Askus.Store.Infrastructure.Interface.Exceptions;
using Askus.Store.Infrastructure.Interface.Repositories;
using Askus.Store.Infrastructure.Interface.Services;
using Askus.Store.Infrastructure.ViewModel;
using Askus.Store.Models.Page;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Askus.Store.Controllers
{
    public class SectionController : BaseStoreController
    {
        private readonly IDomainRepository<Section> _sectionRepository;

        public SectionController(IDomainRepository<Section> domainRepository)
        {
            _sectionRepository = domainRepository;
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult Map(int id)
        {
            var item = FindItem(id, GetMenuItems());
            return View(item);
        }

        [AjaxOnly]
        [JsonException]
        [HttpGet]
        public async Task<JsonResult> GetSectionList(FilterVM filter)
        {
            if (filter == null)
                filter = new FilterVM() { Skip = 0, Take = MaxPageCount };

            var data = await _sectionRepository.GetFilteredAsync(filter);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        [JsonException]
        [HttpPost]
        public async Task SaveSection(Section model)
        {
            if (string.IsNullOrWhiteSpace(model.Title))
                throw new ValidationException("Поле заголовок обязательно!");

            await _sectionRepository.SaveAsync(model);
        }

        [AjaxOnly]
        [JsonException]
        [HttpPost]
        public async Task Remove(int id)
        {
            var page = await _sectionRepository.GetByIdAsync(id);
            await _sectionRepository.RemoveAsync(page);
        }

        private MenuItemModel FindItem(int id, IEnumerable<MenuItemModel> src)
        {
            foreach(var item in src)
            {
                if (item.SectionId == id)
                    return item;
                else if (item.ChildItems != null)
                {
                    var r = FindItem(id, item.ChildItems);
                    if (r != null)
                        return r;
                }
            }
            return null;
        }

    }
}

Askus.Store/Askus.Store/Views/Page/Index.cshtml
@{
    ViewBag.Title = "Страницы сайта";
}

@section scripts
{
    @Scripts.Render(BundleScriptNames.PagesPage)

    <script>
        var _app = new Askus.PagesPage.App({

            AppSelector: "pageApp",
            EditorSelector: "#editor",

            GetUrl: '@Url.Action("GetList", "Page")',
            SaveUrl: '@Url.Action("Save", "Page")',
            SectionsUrl: '@Url.Action("GetSectionList", "Section")',
            SetPublicationUrl: '@Url.Action("SetPublication", "Page")',
            RemoveUrl: '@Url.Action("Remove", "Page")',
            PageCapacity: 5
    });
    </script>
}
<div id="pageApp">
    <h2>Страницы сайта</h2>
    <p>Редактирование страниц портала</p>

    <!-- filter -->
    <div class="row">
        <div class="col-lg-10">
            @Html.Partial("_Filter")
        </div>
        <div class="col-lg-2">
            <button type="button" class="btn btn-default" data-bind="click: Create">Создать</button>
        </div>
    </div>
    <hr />
    <!-- grid -->
    <div class="row">
        <div class="col-lg-12">
            @Html.Partial("_Grid")
        </div>
    </div>

    <div id="editor" class="hidden">
        @Html.Partial("_Editor")
    </div>
</div>

Askus.Store/Askus.Store/Views/Page/_Editor.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <label class="control-label">Наименование:</label>
        </div>
        <div class="col-lg-8">
            <input type="text" class="form-control" placeholder="Введите наименование" data-bind="value: CurrentItem.Title">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <label class="control-label" for="email">Раздел:</label>
        </div>
        <div class="col-lg-8">
            @*<input type="text" class="form-control" placeholder="Выберите родителя" data-bind="value: ParentSectionId">*@
            <select class="form-control" data-bind="
                    value: CurrentItem.SectionId,
                    options: Sections,
                    optionsText: 'Title',
                    optionsValue: 'Id',
                    valueAllowUnset: true"></select>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <label class="control-label">Controller:</label>
        </div>
        <div class="col-lg-8">
            <input type="text" class="form-control" data-bind="value: CurrentItem.ControllerName">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <label class="control-label" for="titleTxb">Action:</label>
        </div>
        <div class="col-lg-8">
            <input type="text" class="form-control" data-bind="value: CurrentItem.ActionName">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <label class="control-label" for="titleTxb">Key:</label>
        </div>
        <div class="col-lg-8">
            <input type="text" class="form-control" data-bind="value: CurrentItem.Key">
        </div>
    </div>
</div>

Askus.Store/Askus.Store/Views/Page/_Grid.cshtml
<table class="table table-hover table-responsive">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Раздел</th>
            <th>Controller</th>
            <th>Action</th>
            <th>Key</th>
            <th>Публикация</th>
            <th></th>
        </tr>
    </thead>
    <tbody data-bind="foreach: Items">
        <tr>
            <td data-bind="text: Title"></td>
            <td data-bind="text: $root.GetSectionTitle(SectionId())"></td>
            <td data-bind="text: ControllerName"></td>
            <td data-bind="text: ActionName"></td>
            <td data-bind="text: Key"></td>
            <td data-bind="text: IsPublished"></td>
            <td>
                <button type="button" class="btn btn-default btn-sm" data-bind="click: function(){$root.SetPublication($data)}">
                    <span class="glyphicon glyphicon-bookmark"></span>
                </button>
                <button type="button" class="btn btn-default btn-sm" data-bind="click: function(){$root.Edit($data)}">
                    <span class="glyphicon glyphicon-edit"></span>
                </button>
                <button type="button" class="btn btn-default btn-sm" data-bind="click: function(){$root.Remove($data)}">
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7" data-bind="with: Filter">

                <ul class="pagination" data-bind="foreach: AvailablePages, visible: AvailablePages().length > 1">
                    <li><a href="#" data-bind="text: ($data + 1), click: $parent.SetPage($data)"></a></li>
                </ul>

            </td>
        </tr>
    </tfoot>
</table>